HotelBookSystem.Web/Controllers/AmenityController.cs
using System.Diagnostics;
using HotelBookSystem.Application.Common.Interfaces;
using HotelBookSystem.Application.Utility;
using HotelBookSystem.Domain.Entities;
using HotelBookSystem.Infrastructure.Data;
using HotelBookSystem.Web.Models;
using HotelBookSystem.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static System.Net.Mime.MediaTypeNames;

namespace HotelBookSystem.Web.Controllers
{
    [Authorize(Roles = StaticDetails.AdminRole)]
    public class AmenityController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AmenityController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var amenities = _unitOfWork.Amenity.GetAll(includeProperties: "Hotel");
            return View(amenities);
        }

        [HttpGet]
        public IActionResult Create()
        {
            AmenityVM amenityVM = new()
            {
                HotelList = _unitOfWork.Hotel.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };
            return View(amenityVM);
        }

        [HttpPost]
        public IActionResult Create(AmenityVM amenityVM)
        {
            if (ModelState.IsValid)
            {
                if (amenityVM.Amenity is not null)
                {
                    _unitOfWork.Amenity.Add(amenityVM.Amenity);
                    _unitOfWork.Save();
                    TempData["success"] = "Успешно добавлено";
                    return RedirectToAction(nameof(Index));
                }
            }

            amenityVM.HotelList = _unitOfWork.Hotel.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });

            return View(amenityVM);
        }

        [HttpGet]
        public IActionResult Update(int amenityId)
        {
            AmenityVM amenityVM = new()
            {
                HotelList = _unitOfWork.Hotel.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),

                Amenity = _unitOfWork.Amenity.Get(u => u.Id == amenityId)
            };

            if (amenityVM.Amenity is null)
            {
                RedirectToAction("Error", "Home");
            }

            return View(amenityVM);
        }

        [HttpPost]
        public IActionResult Update(AmenityVM amenityVM)
        {
            if (ModelState.IsValid)
            {
                if (amenityVM.Amenity is not null)
                {
                    _unitOfWork.Amenity.Update(amenityVM.Amenity);
                    _unitOfWork.Save();
                    TempData["success"] = "Успешно обновлено";
                    return RedirectToAction(nameof(Index));
                }
            }

            amenityVM.HotelList = _unitOfWork.Hotel.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });

            return View(amenityVM);
        }

        [HttpGet]
        public IActionResult Delete(int amenityId)
        {
            AmenityVM amenityVM = new()
            {
                HotelList = _unitOfWork.Hotel.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),

                Amenity = _unitOfWork.Amenity.Get(u => u.Id == amenityId)
            };

            if (amenityVM.Amenity is null)
            {
                RedirectToAction("Error", "Home");
            }

            return View(amenityVM);
        }

        [HttpPost]
        public IActionResult Delete(AmenityVM amenityVM)
        {
            if (amenityVM.Amenity is not null)
            {
                Amenity? objFromDb = _unitOfWork.Amenity
                    .Get(u => u.Id == amenityVM.Amenity.Id);

                if (objFromDb is not null)
                {
                    _unitOfWork.Amenity.Remove(objFromDb);
                    _unitOfWork.Save();
                    TempData["success"] = "Успешно удалено";
                    return RedirectToAction("Index");
                }
            }

            return View(amenityVM);
        }
    }
}

HotelBookSystem.Web/Controllers/BookingController.cs
using System.Security.Claims;
using HotelBookSystem.Application.Common.Interfaces;
using HotelBookSystem.Application.Utility;
using HotelBookSystem.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using Stripe.Checkout;

namespace HotelBookSystem.Web.Controllers
{
    [Authorize]
    public class BookingController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BookingController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult FinalizeBooking(int hotelId, DateOnly checkInDate, int numberOfNights)
        {
            var claimsIdentity = User.Identity as ClaimsIdentity;
            var userId = claimsIdentity?.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            ApplicationUser user = _unitOfWork.User.Get(u => u.Id == userId);

            Booking booking = new()
            {
                HotelId = hotelId,
                Hotel = _unitOfWork.Hotel.Get(u => u.Id == hotelId, includeProperties: "Amenities"),
                CheckInDate = checkInDate,
                CheckOutDate = checkInDate.AddDays(numberOfNights),
                NumberOfNights = numberOfNights,
                UserId = userId ?? "",
                Name = user.Name,
                Email = user.Email ?? "",
                PhoneNumber = user.PhoneNumber,
            };
            booking.TotalCost = booking.Hotel.Price * numberOfNights;
            return View(booking);
        }

        [HttpPost]
        public IActionResult FinalizeBooking(Booking booking)
        {
            if (string.IsNullOrEmpty(booking.PhoneNumber))
            {
                ModelState.AddModelError("PhoneNumber", "Введите номер телефона");
            }
            if (ModelState.IsValid)
            {
                var hotel = _unitOfWork.Hotel.Get(u => u.Id == booking.HotelId);

                booking.TotalCost = hotel.Price * booking.NumberOfNights;
                booking.Status = StaticDetails.StatusPending;
                booking.BookingDate = DateOnly.FromDateTime(DateTime.Now);

                _unitOfWork.Booking.Add(booking);
                _unitOfWork.Save();

                var domain = Request.Scheme + "://" + Request.Host.Value;
                var options = new SessionCreateOptions
                {
                    LineItems = new List<SessionLineItemOptions>(),

                    Mode = "payment",
                    SuccessUrl = domain + $"/booking/BookingConfirmation?bookingId={booking.Id}",
                    CancelUrl = domain + $"/booking/FinalizeBooking?hotelId={booking.HotelId}&" +
                    $"checkInDate={booking.CheckInDate}&numberOfNights={booking.NumberOfNights}",
                };

                options.LineItems.Add(new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        Currency = "rub",
                        UnitAmount = (long)(booking.TotalCost * 100),
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = booking.Name,

                        }
                    },
                    Quantity = 1
                });

                var service = new SessionService();
                Session session = service.Create(options);
                Response.Headers.Append("Location", session.Url);

                _unitOfWork.Booking.UpdateStripePaymentId(booking.Id, session.Id, session.PaymentIntentId);
                _unitOfWork.Save();

                return new StatusCodeResult(303);
            }
            booking.Hotel = _unitOfWork.Hotel.Get(u => u.Id == booking.HotelId, includeProperties: "Amenities");
            booking.TotalCost = booking.Hotel.Price * booking.NumberOfNights;
            booking.User = _unitOfWork.User.Get(u => u.Id == booking.UserId);
            return View(booking);
        }

        [HttpGet]
        public IActionResult BookingConfirmation(int bookingId)
        {
            Booking bookingFromDb = _unitOfWork.Booking.Get(u => u.Id == bookingId,
                includeProperties: "User,Hotel");

            if (string.Equals(bookingFromDb.Status, StaticDetails.StatusPending))
            {
                var service = new SessionService();
                Session session = service.Get(bookingFromDb.StripeSessionId);

                if (string.Equals(session.PaymentStatus, "paid"))
                {
                    _unitOfWork.Booking.UpdateStatus(bookingId, StaticDetails.StatusApproved);
                    _unitOfWork.Booking.UpdateStripePaymentId(bookingId, session.Id, session.PaymentIntentId);
                    _unitOfWork.Save();
                }
            }
            return View(bookingId);
        }

        [HttpGet]
        public IActionResult BookingDetails(int bookingId)
        {
            Booking bookingFromDb = _unitOfWork.Booking.Get(u => u.Id == bookingId,
                includeProperties: "User,Hotel");
            if (bookingFromDb is null)
            {
                return NotFound();
            }
            return View(bookingFromDb);
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<string> statusList = new()
            {
                StaticDetails.StatusPending,
                StaticDetails.StatusApproved,
                StaticDetails.StatusCheckedIn,
                StaticDetails.StatusCompleted,
                StaticDetails.StatusCancelled,
                StaticDetails.StatusRefunded
            };
            return View(statusList);
        }

        // ==================================== API CALLS ====================================
        #region API Calls
        [HttpGet]
        public IActionResult GetAll(string status)
        {
            IEnumerable<Booking> bookings;

            if (User.IsInRole(StaticDetails.AdminRole))
            {
                bookings = _unitOfWork.Booking.GetAll(includeProperties: "User,Hotel");
            }
            else
            {
                var claimsIdentity = User.Identity as ClaimsIdentity;
                var userId = claimsIdentity?.FindFirst(ClaimTypes.NameIdentifier)?.Value;

                if (userId is null) 
                {
                    return Json(new { data = Enumerable.Empty<Booking>() });
                }

                bookings = _unitOfWork.Booking.GetAll(u => u.UserId == userId, includeProperties: "User,Hotel");
            }
            if (!string.IsNullOrEmpty(status))
            {
                bookings = bookings.Where(u => u.Status != null && u.Status.Equals(status, StringComparison.OrdinalIgnoreCase));
            }
            return Json(new { data = bookings });
        }
        #endregion
    }
}

HotelBookSystem.Web/Controllers/HotelController.cs
using System.Diagnostics;
using HotelBookSystem.Application.Common.Interfaces;
using HotelBookSystem.Application.Utility;
using HotelBookSystem.Domain.Entities;
using HotelBookSystem.Infrastructure.Data;
using HotelBookSystem.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static System.Net.Mime.MediaTypeNames;

namespace HotelBookSystem.Web.Controllers
{
    [Authorize(Roles = StaticDetails.AdminRole)]
    public class HotelController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IImageValidator _imageValidator;

        public HotelController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment, IImageValidator imageValidator)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
            _imageValidator = imageValidator;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var Hotels = _unitOfWork.Hotel.GetAll();
            return View(Hotels);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Hotel obj)
        {
            if (obj.Name == obj.Description)
            {
                ModelState.AddModelError("name", "Описание должно отличаться от имени");
            }

            _imageValidator.Validate(obj.Image, ModelState);

            if (ModelState.IsValid)
            {
                if(obj.Image is not null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
                    var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\HotelImages");

                    using var fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create);
                    obj.Image.CopyTo(fileStream);

                    obj.ImageUrl = @"\images\HotelImages\" + fileName;
                }
                else
                {
                    obj.ImageUrl = "https://placehold.co/600x400";
                }


                _unitOfWork.Hotel.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Успешно создано";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [HttpGet]
        public IActionResult Update(int hotelId)
        {
            Hotel? item = _unitOfWork.Hotel.Get(u => u.Id == hotelId);
            if (item is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(item);
        }

        [HttpPost]
        public IActionResult Update(Hotel obj)
        {
            if (obj.Name == obj.Description)
            {
                ModelState.AddModelError("name", "Описание должно отличаться от имени");
            }

            _imageValidator.Validate(obj.Image, ModelState);

            if (ModelState.IsValid && obj.Id > 0)
            {
                if (obj.Image is not null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
                    var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\HotelImages");

                    if (!string.IsNullOrEmpty(obj.ImageUrl))
                    {
                        var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));

                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using var fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create);
                    obj.Image.CopyTo(fileStream);

                    obj.ImageUrl = @"\images\HotelImages\" + fileName;
                }

                _unitOfWork.Hotel.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Успешно обновлено";
                return RedirectToAction(nameof(Index));
            }
            return View(obj);
        }

        [HttpGet]
        public IActionResult Delete(int hotelId)
        {
            Hotel? obj = _unitOfWork.Hotel.Get(u => u.Id == hotelId);
            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(obj);
        }

        [HttpPost]
        public IActionResult Delete(Hotel obj)
        {
            Hotel? objFromDb = _unitOfWork.Hotel.Get(u => u.Id == obj.Id);
            if (objFromDb is not null)
            {
                if (!string.IsNullOrEmpty(objFromDb.ImageUrl))
                {
                    var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));

                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                _unitOfWork.Hotel.Remove(objFromDb);
                _unitOfWork.Save();
                TempData["success"] = "Успешно удалено";
                return RedirectToAction(nameof(Index));
            }
            return View(obj);
        }
    }
}

HotelBookSystem.Web/Views/Shared/_HotelDetails.cshtml
@model Hotel

@{
    bool useTextDark = ViewData["UseTextDark"] as bool? ?? false;
}

<div style="position: relative; z-index: 1;">
    <div class="row">
        <div class="col-12 col-md-5">
            <div style="width: 100%; aspect-ratio: 1 / 1; overflow: hidden; border-radius: 50%;">
                <img src="@Model.ImageUrl" style="width: 100%; height: 100%; object-fit: cover;" />
            </div>
        </div>
        <div class="col-12 col-md-7">
            <div class="row p-2">
                <div class="col-12">
                    <p class="card-title" style="font-size:xx-large; color: #0076bd;">@Model.Name</p>
                    <p class="card-text @(useTextDark ? "text-dark" : "")" style="font-size:large">
                        @Html.Raw(Model.Description)
                    </p>
                    @if (Model.Amenities != null && Model.Amenities.Count() > 0)
                    {
                        <p class="h5 @(useTextDark ? "text-dark" : "text-white")">Hotel Amenities</p>
                        <ul>
                            @foreach (var amenity in Model.Amenities)
                            {
                                <li class="@(useTextDark ? "text-dark" : "")">@amenity.Name</li>
                            }
                        </ul>
                    }
                </div>
            </div>
            <div class="row col-12">
                <div class="text-end p-0 pt-3 m-0">
                    <span class="float-right @(useTextDark ? "text-dark" : "")">Вместимость : @Model.Occupancy человек </span><br />
                    <p class="text-warning font-weight-bold pt-1">
                        USD
                        <span>
                            @Model.Price.ToString() / ночь
                        </span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

HotelBookSystem.Web/Views/Shared/_HotelList.cshtml
@model HomeVM

<div id="hotelList">
    @foreach (var hotel in Model.Hotels)
    {
        <div class="container py-0">
            <article class="postcard dark blue">
                <a class="postcard__img_link">
                    <img class="postcard__img" src="@hotel.ImageUrl" />
                </a>
                <div class="postcard__text">
                    <h1 class="postcard__title blue">@hotel.Name</h1>
                    <div class="postcard__subtitle small">
                        <time datetime="2020-05-25 12:00:00">
                            <i class="fas fa-calendar-alt mr-2"></i>Mon, May 25th 2020
                        </time>
                    </div>
                    <div class="postcard__bar"></div>
                    <div class="postcard__preview-txt">@hotel.Description</div>
                    <ul class="postcard__tagbox">
                        <li class="tag__item" data-bs-toggle="modal" data-bs-target="#modal-@(hotel.Id)">Details</li>
                    </ul>
                    @if (!hotel.IsAvaliable || Model.CheckInDate <= DateOnly.FromDateTime(DateTime.Now))
                    {
                        <a disabled class="btn btn-outline-warning">
                            Недоступно
                        </a>
                    }
                    else
                    {
                        <a asp-controller="Booking" asp-action="FinalizeBooking"
                        class="btn btn-outline-info" asp-route-hotelId="@hotel.Id"
                           asp-route-checkInDate="@Model.CheckInDate.ToString("yyyy-MM-dd")"
                        asp-route-numberOfNights="@Model.NumberOfNights">
                            Забронировать
                        </a>
                    }
                </div>
            </article>
        </div>

        <div class="modal fade" id="modal-@(hotel.Id)" tabindex="-1" aria-labelledby="DetailsModal" aria-hidden="true">
            <div class="modal-dialog modal-xl">
                <div class="modal-content dark blue">
                    <div class="modal-header border-0 dark blue">
                        <h1 class="modal-title fs-3 text-light mx-auto" style="position: relative; z-index: 1;" id="DetailsModal">Подробная информация</h1>
                    </div>
                    <div class="modal-body text-light m-0 dark blue">
                        <partial name="_HotelDetails" model="@hotel" />
                    </div>
                    <div class="modal-footer border-0 text-light dark blue">
                        <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

HotelBookSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HotelBookSystem.Web</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/test.css" />
    <link rel="stylesheet" href="~/HotelBookSystem.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" integrity="sha384-tViUnnbYAV00FLIhhi3v/dWt3Jxw4gZQcNoSCxCIFNJVCx7/D55/wXsrNIRANwdD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/spinner.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/css/dataTables.bootstrap.min.css" integrity="sha512-BMbq2It2D3J17/C7aRklzOODG1IQ3+MHw3ifzBHMBwGO/0yUqYmsStgBjI0z5EYlaDEFnvYV7gNYdD3vFLRKsA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 dark blue">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" width="35px;"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Hotel" asp-action="Index">Hotel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="HotelNumber" asp-action="Index">HotelNumber</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Amenity" asp-action="Index">Amenity</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Booking" asp-action="Index" asp-route-status="@StaticDetails.StatusApproved">Bookings</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="loading" style="display: none"></div>
            <partial name="_Notification">

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js" integrity="sha512-BkpSL20WETFylMrcirBahHfSnY++H2O1W+UnEEO4yNIl+jI2+zowyoGJpbtk6bx97fBXf++WJHSSK2MV4ghPcg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HotelBookSystem.Web/Views/Shared/_Notification.cshtml
@if(TempData["error"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}

@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}