HotelBookSystem.Web/Controllers/HotelController.cs
using System.Diagnostics;
using HotelBookSystem.Application.Common.Interfaces;
using HotelBookSystem.Application.Utility;
using HotelBookSystem.Domain.Entities;
using HotelBookSystem.Infrastructure.Data;
using HotelBookSystem.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static System.Net.Mime.MediaTypeNames;

namespace HotelBookSystem.Web.Controllers
{
    [Authorize(Roles = StaticDetails.AdminRole)]
    public class HotelController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IImageValidator _imageValidator;

        public HotelController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment, IImageValidator imageValidator)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
            _imageValidator = imageValidator;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var Hotels = _unitOfWork.Hotel.GetAll();
            return View(Hotels);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Hotel obj)
        {
            if (obj.Name == obj.Description)
            {
                ModelState.AddModelError("name", "Описание должно отличаться от имени");
            }

            _imageValidator.Validate(obj.Image, ModelState);

            if (ModelState.IsValid)
            {
                if(obj.Image is not null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
                    var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\HotelImages");

                    using var fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create);
                    obj.Image.CopyTo(fileStream);

                    obj.ImageUrl = @"\images\HotelImages\" + fileName;
                }
                else
                {
                    obj.ImageUrl = "https://placehold.co/600x400";
                }


                _unitOfWork.Hotel.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Успешно создано";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [HttpGet]
        public IActionResult Update(int hotelId)
        {
            Hotel? item = _unitOfWork.Hotel.Get(u => u.Id == hotelId);
            if (item is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(item);
        }

        [HttpPost]
        public IActionResult Update(Hotel obj)
        {
            if (obj.Name == obj.Description)
            {
                ModelState.AddModelError("name", "Описание должно отличаться от имени");
            }

            _imageValidator.Validate(obj.Image, ModelState);

            if (ModelState.IsValid && obj.Id > 0)
            {
                if (obj.Image is not null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
                    var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\HotelImages");

                    if (!string.IsNullOrEmpty(obj.ImageUrl))
                    {
                        var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));

                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using var fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create);
                    obj.Image.CopyTo(fileStream);

                    obj.ImageUrl = @"\images\HotelImages\" + fileName;
                }

                _unitOfWork.Hotel.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Успешно обновлено";
                return RedirectToAction(nameof(Index));
            }
            return View(obj);
        }

        [HttpGet]
        public IActionResult Delete(int hotelId)
        {
            Hotel? obj = _unitOfWork.Hotel.Get(u => u.Id == hotelId);
            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(obj);
        }

        [HttpPost]
        public IActionResult Delete(Hotel obj)
        {
            Hotel? objFromDb = _unitOfWork.Hotel.Get(u => u.Id == obj.Id);
            if (objFromDb is not null)
            {
                if (!string.IsNullOrEmpty(objFromDb.ImageUrl))
                {
                    var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));

                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                _unitOfWork.Hotel.Remove(objFromDb);
                _unitOfWork.Save();
                TempData["success"] = "Успешно удалено";
                return RedirectToAction(nameof(Index));
            }
            return View(obj);
        }
    }
}

HotelBookSystem.Web/Views/Hotel/Create.cshtml
@model Hotel

<div class="card mt-2 mx-auto p-4 bg-light w-100">
    <div class="card-header border-0 text-light text-center dark blue"
         style="background-image: linear-gradient(-30deg, rgba(0, 118, 189, 0.1), transparent 100%);">
        <h3 class="mb-0">Создать отель</h3>
    </div>
    <div class="card-body bg-light">
        <div class="container">
            <form method="post" class="row" enctype="multipart/form-data">
                <div class="controls">
                    <div class="row">
                        <div class="form-floating py-1 col-12">
                            <input asp-for="Name" class="form-control border shadow" />
                            <label asp-for="Name" class="ms-2"></label>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-floating py-1 col-12">
                                <input asp-for="Price" class="form-control border shadow" />
                                <label asp-for="Price" class="ms-2"></label>
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-floating py-1 col-12">
                                <input asp-for="Occupancy" class="form-control border shadow" />
                                <label asp-for="Occupancy" class="ms-2"></label>
                                <span asp-validation-for="Occupancy" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-floating py-1 col-12">
                            <textarea asp-for="Description"
                                      class="form-control border shadow auto-resize"
                                      rows="1"
                                      style="overflow:hidden;"></textarea>
                            <label asp-for="Description" class="ms-2"></label>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-floating py-1 col-12">
                            <input asp-for="ImageUrl" hidden class="form-control border shadow" />
                            <input asp-for="Image" class="form-control border shadow" />
                            <label asp-for="ImageUrl" class="ms-2"></label>
                            <span asp-validation-for="Image" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row pt-2">
                        <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-success w-100">
                                <i class="bi bi-check-circle"></i> Создать
                            </button>
                        </div>
                        <div class="col-6 col-md-3">
                            <a asp-controller="Hotel" asp-action="Index" class="btn btn-secondary w-100">
                                <i class="bi bi-x-circle"></i> Отмена
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"></partial>
        <script src="~/js/textarea_resize.js"></script>
    }
}

HotelBookSystem.Web/Views/Hotel/Delete.cshtml
@model Hotel

<div class="card mt-2 mx-auto p-4 bg-light w-100">
    <div class="card-header border-0 text-light text-center dark blue"
         style="background-image: linear-gradient(-30deg, rgba(0, 118, 189, 0.1), transparent 100%);">
        <h3 class="mb-0">Удалить отель</h3>
    </div>
    <div class="card-body bg-light">
        <div class="container">
            <form method="post" class="row" enctype="multipart/form-data">
                <input asp-for="Id" hidden />
                <div class="col-10">
                    <div class="controls">
                        <div class="row">
                            <div class="form-floating py-1 col-12">
                                <input asp-for="Name" disabled class="form-control border shadow" />
                                <label asp-for="Name" class="ms-2"></label>
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-floating py-1 col-12">
                                    <input asp-for="Price" disabled class="form-control border shadow" />
                                    <label asp-for="Price" class="ms-2"></label>
                                    <span asp-validation-for="Price" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating py-1 col-12">
                                    <input asp-for="Occupancy" disabled class="form-control border shadow" />
                                    <label asp-for="Occupancy" class="ms-2"></label>
                                    <span asp-validation-for="Occupancy" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-floating py-1 col-12">
                                <textarea asp-for="Description"
                                          disabled class="form-control border shadow auto-resize"
                                          rows="1"
                                          style="overflow:hidden;"></textarea>
                                <label asp-for="Description" class="ms-2"></label>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-floating py-1 col-12">
                                <input asp-for="ImageUrl" hidden class="form-control border shadow" />
                                <input asp-for="Image" disabled class="form-control border shadow" />
                                <label asp-for="ImageUrl" class="ms-2"></label>
                                <span asp-validation-for="Image" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row pt-2">
                            <div class="col-6 col-md-3">
                                <button type="submit" class="btn btn-danger w-100">
                                    <i class="bi bi-check-circle"></i> Удалить
                                </button>
                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="Hotel" asp-action="Index" class="btn btn-secondary w-100">
                                    <i class="bi bi-x-circle"></i> Отмена
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    <img src="@Model.ImageUrl" class="w-100" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial"></partial>
        <script src="~/js/textarea_resize.js"></script>
    }
}

HotelBookSystem.Web/Views/Hotel/Index.cshtml
@model List<Hotel>

<div class="card shadow my-5">
    <div class="card-header border-0 text-light text-center dark blue"
         style="background-image: linear-gradient(-30deg, rgba(0, 118, 189, 0.1), transparent 100%);">
        <h3 class="mb-0">Отели</h3>
    </div>
    <table class="table mb-0">
        <thead>
            <tr>
                <th class="p-0" scope="col"></th>
                <th class="p-0" scope="col"></th>
                <th class="p-0" scope="col" width="30%"></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var hotel in Model)
            {
                <tr>
                    <td>
                        <div style="width: 60px; aspect-ratio: 1 / 1; overflow: hidden; border-radius: 50%;">
                            <img src="@hotel.ImageUrl" style="width: 100%; height: 100%; object-fit: cover;" />
                        </div>
                    </td>
                    <td style="font-size: 20px; vertical-align: middle;">
                        <div class="d-flex align-items-center" style="height: 100%;">
                            @hotel.Name
                        </div>
                    </td>
                    <td class="align-middle text-center">
                        <div class="d-flex justify-content-center align-items-center gap-2 w-100">
                            <a asp-controller="Hotel" asp-action="Update" asp-route-hotelId="@hotel.Id"
                               class="btn btn-success rounded">
                                <i class="bi bi-pencil-square"></i> Изменить
                            </a>
                            <a asp-controller="Hotel" asp-action="Delete" asp-route-hotelId="@hotel.Id"
                               class="btn btn-danger rounded">
                                <i class="bi bi-trash-fill"></i> Удалить
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="d-flex w-25" style="float: right;">
    <a asp-controller="Hotel" asp-action="Create" class="btn btn-dark rounded border w-100">
        <i class="bi bi-plus-circle"></i> Create
    </a>
</div>

HotelBookSystem.Web/Views/Hotel/Update.cshtml
@model Hotel

<div class="card mt-2 mx-auto p-4 bg-light w-100">
    <div class="card-header border-0 text-light text-center dark blue"
         style="background-image: linear-gradient(-30deg, rgba(0, 118, 189, 0.1), transparent 100%);">
        <h3 class="mb-0">Изменить отель</h3>
    </div>
    <div class="card-body bg-light">
        <div class="container">
            <form method="post" class="row" enctype="multipart/form-data">
                <input asp-for="Id" hidden />
                <div class="col-10">
                    <div class="controls">
                        <div class="row">
                            <div class="form-floating py-1 col-12">
                                <input asp-for="Name" class="form-control border shadow" />
                                <label asp-for="Name" class="ms-2"></label>
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-floating py-1 col-12">
                                    <input asp-for="Price" class="form-control border shadow" />
                                    <label asp-for="Price" class="ms-2"></label>
                                    <span asp-validation-for="Price" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating py-1 col-12">
                                    <input asp-for="Occupancy" class="form-control border shadow" />
                                    <label asp-for="Occupancy" class="ms-2"></label>
                                    <span asp-validation-for="Occupancy" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-floating py-1 col-12">
                                <textarea asp-for="Description"
                                          class="form-control border shadow auto-resize"
                                          rows="1"
                                          style="overflow:hidden;"></textarea>
                                <label asp-for="Description" class="ms-2"></label>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-floating py-1 col-12">
                                <input asp-for="ImageUrl" hidden class="form-control border shadow" />
                                <input asp-for="Image" class="form-control border shadow" />
                                <label asp-for="ImageUrl" class="ms-2"></label>
                                <span asp-validation-for="Image" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row pt-2">
                            <div class="col-6 col-md-3">
                                <button type="submit" class="btn btn-warning w-100">
                                    <i class="bi bi-check-circle"></i> Обновить
                                </button>
                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="Hotel" asp-action="Index" class="btn btn-secondary w-100">
                                    <i class="bi bi-x-circle"></i> Отмена
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    <img src="@Model.ImageUrl" class="w-100" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial"></partial>
        <script src="~/js/textarea_resize.js"></script>
    }
}