HotelBookSystem.Web/Controllers/HotelNumberController.cs
using System.Diagnostics;
using HotelBookSystem.Application.Common.Interfaces;
using HotelBookSystem.Application.Utility;
using HotelBookSystem.Domain.Entities;
using HotelBookSystem.Infrastructure.Data;
using HotelBookSystem.Infrastructure.Repository;
using HotelBookSystem.Web.Models;
using HotelBookSystem.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HotelBookSystem.Web.Controllers
{
    [Authorize(Roles = StaticDetails.AdminRole)]
    public class HotelNumberController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public HotelNumberController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        [HttpGet]
        public IActionResult Index()
        {
            var hotelNumbers = _unitOfWork.HotelNumber.GetAll(includeProperties: "Hotel"); 
            return View(hotelNumbers);
        }

        [HttpGet]
        public IActionResult Create()
        {
            HotelNumberVM hotelNumberVM = new()
            {
                HotelList = _unitOfWork.Hotel.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };
            return View(hotelNumberVM);
        }

        [HttpPost]
        public IActionResult Create(HotelNumberVM hotelNumberVM)
        {
            if (hotelNumberVM.HotelNumber is null)
            {
                hotelNumberVM.HotelList = _unitOfWork.Hotel.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                });
                return View(hotelNumberVM);
            }

            bool roomNumberExists = _unitOfWork.HotelNumber.Any(u => u.Hotel_Number == hotelNumberVM.HotelNumber.Hotel_Number);

            if (ModelState.IsValid && !roomNumberExists)
            {
                _unitOfWork.HotelNumber.Add(hotelNumberVM.HotelNumber);
                _unitOfWork.Save();
                TempData["success"] = "Успешно создано";
                return RedirectToAction(nameof(Index));
            }

            if (roomNumberExists)
            {
                TempData["error"] = "Такая комната уже существует";
            }

            hotelNumberVM.HotelList = _unitOfWork.Hotel.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });

            return View(hotelNumberVM);
        }

        [HttpGet]
        public IActionResult Update(int hotelNumberId)
        {
            HotelNumberVM hotelNumberVM = new()
            {
                HotelList = _unitOfWork.Hotel.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),

                HotelNumber = _unitOfWork.HotelNumber.Get(u => u.Hotel_Number == hotelNumberId)
            };

            if (hotelNumberVM.HotelNumber is null)
            {
                RedirectToAction("Error", "Home");
            }

            return View(hotelNumberVM);
        }

        [HttpPost]
        public IActionResult Update(HotelNumberVM hotelNumberVM)
        {
            if (ModelState.IsValid)
            {
                if (hotelNumberVM.HotelNumber is not null)
                {
                    _unitOfWork.HotelNumber.Update(hotelNumberVM.HotelNumber);
                    _unitOfWork.Save();
                    TempData["success"] = "Успешно сохранено";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["error"] = "Ошибка: номер отеля не найден.";
                }
            }

            hotelNumberVM.HotelList = _unitOfWork.Hotel.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });

            return View(hotelNumberVM);
        }

        [HttpGet]
        public IActionResult Delete(int hotelNumberId)
        {
            HotelNumberVM hotelNumberVM = new()
            {
                HotelList = _unitOfWork.Hotel.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),

                HotelNumber = _unitOfWork.HotelNumber.Get(u => u.Hotel_Number == hotelNumberId)
            };

            if (hotelNumberVM.HotelNumber is null)
            {
                RedirectToAction("Error", "Home");
            }

            return View(hotelNumberVM);
        }

        [HttpPost]
        public IActionResult Delete(HotelNumberVM hotelNumberVM)
        {
            HotelNumber? objFromDb = _unitOfWork.HotelNumber
                .Get(u => u.Hotel_Number == hotelNumberVM.HotelNumber.Hotel_Number);

            if (objFromDb is not null)
            {
                _unitOfWork.HotelNumber.Remove(objFromDb);
                _unitOfWork.Save();
                TempData["success"] = "Успешно удалено";
                return RedirectToAction("Index");
            }

            return View(hotelNumberVM);
        }

    }
}

HotelBookSystem.Web/Views/HotelNumber/Create.cshtml
@model HotelNumberVM

<div class="card mt-2 mx-auto p-4 bg-light w-100">
    <div class="card-header border-0 text-light text-center dark blue"
         style="background-image: linear-gradient(-30deg, rgba(0, 118, 189, 0.1), transparent 100%);">
        <h3 class="mb-0">Создать номер</h3>
    </div>
    <div class="card-body bg-light">
        <div class="container">
            <form method="post" class="row" enctype="multipart/form-data">
                <div class="controls">
                    <div class="row">
                        <div class="form-floating py-1 col-12">
                            <select asp-for="@Model.HotelNumber.HotelId" asp-items="@Model.HotelList"
                                    class="form-control border shadow">
                                <option disabled selected>____Выберите отель____</option>
                            </select>
                            <label asp-for="HotelNumber.HotelId" class="ms-2"></label>
                            <span asp-validation-for="HotelNumber.HotelId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-floating py-1 col-12">
                            <div class="form-floating py-1 col-12">
                                <input asp-for="HotelNumber.Hotel_Number" class="form-control border shadow" />
                                <label asp-for="HotelNumber.Hotel_Number" class="ms-2"></label>
                                <span asp-validation-for="HotelNumber.Hotel_Number" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-floating py-1 col-12">
                            <textarea asp-for="HotelNumber.Details"
                                      class="form-control border shadow auto-resize"
                                      rows="1"
                                      style="overflow:hidden;"></textarea>
                            <label asp-for="HotelNumber.Details" class="ms-2"></label>
                            <span asp-validation-for="HotelNumber.Details" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row pt-2">
                        <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-success w-100">
                                <i class="bi bi-check-circle"></i> Создать
                            </button>
                        </div>
                        <div class="col-6 col-md-3">
                            <a asp-controller="HotelNumber" asp-action="Index" class="btn btn-secondary w-100">
                                <i class="bi bi-x-circle"></i> Отмена
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial"></partial>
        <script src="~/js/textarea_resize.js"></script>
    }
}

HotelBookSystem.Web/Views/HotelNumber/Delete.cshtml
@model HotelNumberVM

<div class="card mt-2 mx-auto p-4 bg-light w-100">
    <div class="card-header border-0 text-light text-center dark blue"
         style="background-image: linear-gradient(-30deg, rgba(0, 118, 189, 0.1), transparent 100%);">
        <h3 class="mb-0">Удалить номер</h3>
    </div>
    <div class="card-body bg-light">
        <div class="container">
            <form method="post" class="row" enctype="multipart/form-data">
                <input asp-for="HotelNumber.Hotel_Number" hidden />
                <div class="controls">
                    <div class="row">
                        <div class="form-floating py-1 col-12">
                            <select disabled asp-for="@Model.HotelNumber.HotelId" asp-items="@Model.HotelList"
                                    class="form-control border shadow">
                                <option disabled selected>____Выберите отель____</option>
                            </select>
                            <label asp-for="HotelNumber.HotelId" class="ms-2"></label>
                            <span asp-validation-for="HotelNumber.HotelId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-floating py-1 col-12">
                            <div class="form-floating py-1 col-12">
                                <input disabled asp-for="HotelNumber.Hotel_Number" class="form-control border shadow" />
                                <label asp-for="HotelNumber.Hotel_Number" class="ms-2"></label>
                                <span asp-validation-for="HotelNumber.Hotel_Number" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-floating py-1 col-12">
                            <textarea disabled asp-for="HotelNumber.Details"
                                      class="form-control border shadow auto-resize"
                                      rows="1"
                                      style="overflow:hidden;"></textarea>
                            <label asp-for="HotelNumber.Details" class="ms-2"></label>
                            <span asp-validation-for="HotelNumber.Details" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row pt-2">
                        <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-danger w-100">
                                <i class="bi bi-check-circle"></i> Удалить
                            </button>
                        </div>
                        <div class="col-6 col-md-3">
                            <a asp-controller="HotelNumber" asp-action="Index" class="btn btn-secondary w-100">
                                <i class="bi bi-x-circle"></i> Отмена
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial"></partial>
        <script src="~/js/textarea_resize.js"></script>
    }
}

HotelBookSystem.Web/Views/HotelNumber/Index.cshtml
@model List<HotelNumber>

<div class="card shadow my-5">
    <div class="card-header border-0 text-light text-center dark blue"
         style="background-image: linear-gradient(-30deg, rgba(0, 118, 189, 0.1), transparent 100%);">
        <h3 class="mb-0">Номера</h3>
    </div>
    <table class="table mb-0">
        <thead>
            <tr>
                <th class="p-0" scope="col"></th>
                <th class="p-0" scope="col"></th>
                <th class="p-0" scope="col"></th>
                <th class="p-0" scope="col" width="30%"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var hotelNumber in Model)
            {
                <tr>
                    <td>
                        <div style="width: 60px; aspect-ratio: 1 / 1; overflow: hidden; border-radius: 50%;">
                            <img src="@hotelNumber.Hotel.ImageUrl" style="width: 100%; height: 100%; object-fit: cover;" />
                        </div>
                    </td>
                    <td style="font-size: 20px; vertical-align: middle;">
                        <div class="d-flex align-items-center" style="height: 100%;">
                            @hotelNumber.Hotel.Name
                        </div>
                    </td>
                    <td style="font-size: 20px; vertical-align: middle;">
                        <div class="d-flex align-items-center" style="height: 100%;">
                            @hotelNumber.Hotel_Number
                        </div>
                    </td>
                    <td class="align-middle text-center">
                        <div class="d-flex justify-content-center align-items-center gap-2 w-100">
                            <a asp-controller="HotelNumber" asp-action="Update" asp-route-hotelNumberId="@hotelNumber.Hotel_Number"
                               class="btn btn-success rounded">
                                <i class="bi bi-pencil-square"></i> Изменить
                            </a>
                            <a asp-controller="HotelNumber" asp-action="Delete" asp-route-hotelNumberId="@hotelNumber.Hotel_Number"
                               class="btn btn-danger rounded">
                                <i class="bi bi-trash-fill"></i> Удалить
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="d-flex w-25" style="float: right;">
    <a asp-controller="HotelNumber" asp-action="Create" class="btn btn-dark rounded border w-100">
        <i class="bi bi-plus-circle"></i> Create
    </a>
</div>

HotelBookSystem.Web/Views/HotelNumber/Update.cshtml
@model HotelNumberVM

<div class="card mt-2 mx-auto p-4 bg-light w-100">
    <div class="card-header border-0 text-light text-center dark blue"
         style="background-image: linear-gradient(-30deg, rgba(0, 118, 189, 0.1), transparent 100%);">
        <h3 class="mb-0">Изменить номер</h3>
    </div>
    <div class="card-body bg-light">
        <div class="container">
            <form method="post" class="row" enctype="multipart/form-data">
                <input asp-for="HotelNumber.Hotel_Number" hidden />
                <div class="controls">
                    <div class="row">
                        <div class="form-floating py-1 col-12">
                            <select asp-for="@Model.HotelNumber.HotelId" asp-items="@Model.HotelList"
                                    class="form-control border shadow">
                                <option disabled selected>____Выберите отель____</option>
                            </select>
                            <label asp-for="HotelNumber.HotelId" class="ms-2"></label>
                            <span asp-validation-for="HotelNumber.HotelId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-floating py-1 col-12">
                            <div class="form-floating py-1 col-12">
                                <input disabled asp-for="HotelNumber.Hotel_Number" class="form-control border shadow" />
                                <label asp-for="HotelNumber.Hotel_Number" class="ms-2"></label>
                                <span asp-validation-for="HotelNumber.Hotel_Number" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-floating py-1 col-12">
                            <textarea asp-for="HotelNumber.Details"
                                      class="form-control border shadow auto-resize"
                                      rows="1"
                                      style="overflow:hidden;"></textarea>
                            <label asp-for="HotelNumber.Details" class="ms-2"></label>
                            <span asp-validation-for="HotelNumber.Details" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row pt-2">
                        <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-warning w-100">
                                <i class="bi bi-check-circle"></i> Изменить
                            </button>
                        </div>
                        <div class="col-6 col-md-3">
                            <a asp-controller="HotelNumber" asp-action="Index" class="btn btn-secondary w-100">
                                <i class="bi bi-x-circle"></i> Отмена
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial"></partial>
        <script src="~/js/textarea_resize.js"></script>
    }
}